sylius_ui:
    events:
        sylius.shop.product.show.right_sidebar:
            blocks:
                product_color: 
                    template: 'bundles/SyliusShopBundle/Product/Show/_productColor.html.twig'
                    priority: 20
